<?php
require_once('app/kernel/Controller.php');

class ItemController extends Controller
{

    public function display()
    {
        parent::display(); // TODO: Change the autogenerated stub
    }

    public function edit($slug)
    {
        Item::getFromSlug($slug);

    }
    public function do_edit()
    {

    }

}
